#!/bin/bash

# Skrypt generuje środowisko chroot z Debianem.
# Generuje skrypty do wykonania pod chroot instalujące i
# ustawiające potrzebne oprogramowanie.
# Potem można wygenerować image systemu do nagrania na pendrive.
#
# Do działania wymagane są programy: debootstrap, debootstick
# zainstalowane na systemie Debian lub pochodnym.

skrypt=`printf '%s\n' "${0##*/}"`
dir="/home/chroot_debian"
subdir="rescue"
#mirror="http://omv1:88/debian/"		# Lokalny mirror (sieć LAN).
mirror="http://deb.debian.org/debian/"

usage()
{
echo "
Jak używać: $skrypt [ -d ] [ -s ] [ -r ] [ -i ] [ -c ]
 -d tworzy na dysku środowisko chroot z Debianem w $dir
 -s tworzy skrypty do wykonania w chroot z Debianem
 -r wejdź do chroot z Debianem
 -i generuje uruchamialny obraz systemu przez debootstick
 -c kasuje z dysku środowisko chroot z Debianem
"
}

dbstrap()
{
sudo mkdir -p $dir
cd $dir
sudo debootstrap --arch=amd64 buster $subdir $mirror
}

debian_chroot()
{
    cd $dir
    #sudo mount proc $subdir/proc -t proc
    #sudo mount sysfs $subdir/sys -t sysfs
    sudo LC_ALL=C chroot $dir/$subdir /bin/bash
    #sudo umount $subdir/proc $subdir/sys
}

stick()
{
    czas=`date +%Y%m%d`
    echo "
    $czas
    "
    cd $dir
    img="deb-rescue-$czas.img"
    sudo debootstick rescue $img
    sudo xz -z -9 -T 0 -v $img
    echo "Wygenerowano obraz $img.xz ..."
}

skrypty_chroot()
{
hdir="$HOME"
mkdir -p ~/tmp
cd ~/tmp

git clone https://github.com/zbychuk79/debian-rescue.git
cd debian-rescue
sudo mv czytaj.txt $dir/$subdir
sudo mv install_script.sh $dir/$subdir
cd ..
rm -rf debian-rescue
}

if [ "$#" = 0 ]; then
    usage
    echo
fi

while [ "$1" != "" ]; do
    case $1 in
        -d )			debstrap="yes"
                                ;;
        -s )			skrypty="yes"
                                ;;
        -r )			chroot_debian="yes"
                                ;;
        -i )			stick="yes"
                                ;;
        -c )			clean="yes"
                                ;;
        * )			usage
                                exit 0
    esac
    shift
done

if [ "$debstrap" = "yes" ]; then
    echo "Generowanie środowiska chroot ..."
    dbstrap
fi

if [ "$skrypty" = "yes" ]; then
    echo "Generowanie skryptów do wykonania w chroot ..."
    skrypty_chroot
fi

if [ "$chroot_debian" = "yes" ]; then
    echo "Wejście do środowiska chroot ..."
    debian_chroot
fi

if [ "$stick" = "yes" ]; then
    echo "Generuję uruchamialny obraz systemu przez debootstick ..."
    stick
fi

if [ "$clean" = "yes" ]; then
    echo "Kasowanie środowiska chroot ..."
    sudo rm -rf $dir/$subdir
    exit 0
fi
