#!/bin/bash

# Wersja RPi dla generowanego obrazu.
#
rpi="bcm2708"
wersja="18.06.8"
#wersja="19.07.3"
link="https://downloads.openwrt.org/releases"

usage()
{
    echo "
Jak używać: wrt [ -w wersja ] [ -c ] | [ -h ]
 -w wersja OpenWRT do budowy (domyślne: $wersja)
 -c czyści swoje pliki z systemu
 -h wyświetlenie tej instrukcji
"
}

if [ "$#" = 0 ]; then
    usage
    echo
fi

while [ "$1" != "" ]; do
    case $1 in
        -w | --wersja )         shift
                                wersja=$1
                                ;;
        -c | --clean )          clean="yes"
                                ;;
        -h | --help )           usage
                                exit
                                ;;
        * )                     usage
                                exit 1
    esac
    shift
done

cd
if [ "$clean" = "yes" ]; then
    echo "Czyszczę ..."
    rm -rf $HOME/wrt-config
    rm -rf $HOME/wrt-$wersja
    rm -rf $HOME/openwrt-$wersja-images
    exit 0
fi

if [ ! -d wrt-config ]; then
    echo
    echo "Nie ma na dysku konfiguracji dla OpenWRT ( katalog wrt-config )."
    echo
    git clone https://github.com/zbychuk79/wrt-config.git
fi

if [ ! -d $HOME/wrt-$wersja/openwrt-imagebuilder-$wersja-brcm2708-$rpi.Linux-x86_64 ]; then
    echo "Pobieram ..."
    mkdir -p $HOME/wrt-$wersja
    cd $HOME/wrt-$wersja
    wget -c $link/$wersja/targets/brcm2708/$rpi/openwrt-imagebuilder-$wersja-brcm2708-$rpi.Linux-x86_64.tar.xz
    tar xvfJ openwrt-imagebuilder-$wersja-brcm2708-$rpi.Linux-x86_64.tar.xz
fi

echo "Generuję obrazy ..."
for ap in ap1; do
    # RPi 1 B + ath9k WiFi USB card
    cd $HOME/wrt-$wersja/openwrt-imagebuilder-$wersja-brcm2708-$rpi.Linux-x86_64
    make image PACKAGES="luci luci-app-firewall luci-base luci-lib-ip luci-lib-jsonc \
    luci-lib-nixio luci-mod-admin-full luci-proto-ipv6 luci-proto-ppp luci-theme-bootstrap \
    mc curl nano kmod-ath9k-htc" FILES=../../wrt-config/$ap/
    mkdir -p $HOME/openwrt-$wersja-images/$ap
    mv bin/targets/brcm2708/$rpi/* $HOME/openwrt-$wersja-images/$ap
    cd
    tar cvfJ $HOME/openwrt-$wersja-images/$ap/$ap-config.tar.xz wrt-config/$ap
done
for ap in ap2 ap3; do
    # RPi Zero W + rtl8152 USB Ethernet
    cd $HOME/wrt-$wersja/openwrt-imagebuilder-$wersja-brcm2708-$rpi.Linux-x86_64
    make image PACKAGES="luci luci-app-firewall luci-base luci-lib-ip luci-lib-jsonc \
    luci-lib-nixio luci-mod-admin-full luci-proto-ipv6 luci-proto-ppp luci-theme-bootstrap \
    mc curl nano kmod-usb-net-rtl8152" FILES=../../wrt-config/$ap/
    mkdir -p $HOME/openwrt-$wersja-images/$ap
    mv bin/targets/brcm2708/$rpi/* $HOME/openwrt-$wersja-images/$ap
    cd
    tar cvfJ $HOME/openwrt-$wersja-images/$ap/$ap-config.tar.xz wrt-config/$ap
done
cp $0 $HOME/openwrt-$wersja-images/
