#!/bin/bash

usage()
{
    echo "
Jak używać: ipxe [ -d ] [ -c ... ] | [ -h ]

 -d ściągnij źródła
 -c kompiluj - jaki iPXE budować
     zbychuk: buduję go dla mojej domowej sieci LAN (autor).
    internet: iPXE dla konfiguracji z poza sieci -zbychuk-.

 -h wyświetlenie tej instrukcji
"
}

if [ "$#" = 0 ]; then
    usage
    exit 1
fi

while [ "$1" != "" ]; do
    case $1 in
        -d )          download="yes"
                                ;;
        -c )          shift
                      net=$1
                      compile="yes"
                                ;;
        -h | --help )           usage
                                exit
                                ;;
        * )                     usage
                                exit 0
    esac
    shift
done

cd
mkdir -p ipxe
mkdir -p ipxe-image

if [ "$download" = "yes" ]; then
    rm -rf ipxe
    git clone git://git.ipxe.org/ipxe.git
    rm -rf ipxe-custom
    git clone https://github.com/zbychuk79/ipxe-custom.git
fi

if [ "$compile" = "yes" ]; then
                       cp ~/ipxe-custom/ipxe-config/general.h ~/ipxe/src/config/general.h
    case $net in
        zbychuk )      cp ~/ipxe-custom/$net/embeded.ipxe ~/ipxe/src/embeded.ipxe
                                ;;
        internet )     cp ~/ipxe-custom/$net/embeded.ipxe ~/ipxe/src/embeded.ipxe
                                ;;
        * )            echo "
Nie podałeś parametru -c [ zbychuk | internet ]
"
                       exit 0
    esac
    mkdir -p ~/ipxe-image/$net
    cd ~/ipxe/src
    make clean
    make all EMBED=embeded.ipxe
    cp bin/ipxe.lkrn bin/ipxe.usb bin/ipxe.iso bin/ipxe.dsk bin/ipxe.pxe ~/ipxe-image/$net
    cp ~/ipxe/src/config/general.h ~/ipxe-image/$net/
    cp embeded.ipxe ~/ipxe-image/$net/
    cp $0 ~/ipxe-image/$net/
fi
